[TAS-66] Shard selection for insertion
isoprophlex/distributed-postgres pull request #18
Opened 2024-08-20 00:59 UTC by AldoRastrelli

# [TAS-66] [Subtask] Elección de Shard para Insertion

## Description
Shard election for insertion query, choosing the shard with the bigger available memory size.

### Changes
- Router keeps a shard_manager which keeps track of the available memory of each shard
- Router asks for MemoryUpdate when creating the health channel and after each time it has send an insertion to a shard
- ShardManager returns always the shard with the bigger available memory size.

- Router has been refactored. Small functions have been added to split bigger ones.
- Unused files have been deleted
- Cargo fmt has been run

### Keep in mind
- There might be a future need of router and shards communicating with other messages. The scope of this task does not include those interactions.

## Checklist
[Check all of the boxes you match, and explain why if not checked]
- [x] New unit tests added. Why (if not):
- [x] All unit tests passed

2024-08-21 00:40 UTC, ncontinanza requested changes

2024-08-21 00:40 UTC, ncontinanza commented on sharding/src/node/memory_manager.rs
> +use futures::future::ErrInto;
```suggestion
```

2024-08-21 00:40 UTC, ncontinanza commented on sharding/src/node/router.rs
> +use crate::node;
```suggestion
```

2024-08-21 00:40 UTC, ncontinanza commented on sharding/src/node/router.rs
> +use super::{node::*, shard};
```suggestion
```

2024-08-21 00:40 UTC, ncontinanza commented on sharding/src/node/shard.rs
> +use std::borrow::BorrowMut;
```suggestion
```

2024-08-21 00:40 UTC, ncontinanza commented on sharding/src/node/shard.rs
> +use crate::node::router::Channel;
```suggestion
```

2024-08-21 00:40 UTC, ncontinanza commented on sharding/src/node/shard.rs
> +use crate::node::{memory_manager, shard};
```suggestion
use crate::node::shard;
```

2024-08-21 00:40 UTC, ncontinanza commented on sharding/src/node/shard.rs
>  use rust_decimal::Decimal;
```suggestion
```

2024-08-21 00:40 UTC, ncontinanza commented on sharding/src/node/shard.rs
>          rw_stream: Arc<RwLock<Option<TcpStream>>>,
This is now unused

2024-08-21 00:40 UTC, ncontinanza commented on sharding/src/node/shard.rs
> +            Err(e) => {
`e` is unused if the print is commented
```suggestion
            Err(_e) => {
```

2024-08-21 00:40 UTC, ncontinanza commented on sharding/src/node/shard.rs
> +        let rows = match self.backend.as_ref().try_lock().unwrap().query(query, &[]) {
```suggestion
        match self.backend.as_ref().try_lock().unwrap().query(query, &[]) {
```

2024-08-21 01:07 UTC, AldoRastrelli commented on sharding/src/node/shard.rs
>          rw_stream: Arc<RwLock<Option<TcpStream>>>,
yet

2024-08-22 15:06 UTC, ncontinanza approved these changes

2024-08-22 15:14 UTC, merged